import type { Product, Review, Vendor } from '../types';

export const MOCK_VENDORS: Vendor[] = [
    {
        id: 'v1',
        userId: 'u1',
        businessName: 'Noor Essentials',
        businessEmail: 'contact@nooressentials.com',
        businessPhone: '+1234567890',
        businessAddress: {
            firstName: 'Ahmed',
            lastName: 'Khan',
            address1: '123 Market St',
            city: 'Dubai',
            state: 'Dubai',
            postalCode: '12345',
            country: 'UAE',
            phone: '+1234567890',
        },
        description: 'Premium quality prayer essentials and perfumes.',
        logo: '/images/products/prayer-rug-1.jpg',
        banner: '/images/hero/hero-bg.jpg',
        status: 'approved',
        rating: 4.8,
        reviewCount: 124,
        totalSales: 450,
        totalOrders: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
        settings: {
            autoFulfill: true,
            notificationPreferences: {}
        }
    },
    {
        id: 'v2',
        userId: 'u2',
        businessName: 'Modest Modern',
        businessEmail: 'hello@modestmodern.com',
        businessPhone: '+0987654321',
        businessAddress: {
            firstName: 'Sarah',
            lastName: 'Ali',
            address1: '456 Fashion Ave',
            city: 'Istanbul',
            state: 'Istanbul',
            postalCode: '34000',
            country: 'Turkey',
            phone: '+0987654321',
        },
        description: 'Contemporary modest fashion for the modern woman.',
        logo: '/images/products/kaftan-1.jpg',
        banner: '/images/hero/hero-bg.jpg',
        status: 'approved',
        rating: 4.6,
        reviewCount: 89,
        totalSales: 320,
        totalOrders: 110,
        createdAt: new Date(),
        updatedAt: new Date(),
        settings: {
            autoFulfill: true,
            notificationPreferences: {}
        }
    },
];

export const MOCK_PRODUCTS: Product[] = [
    // Prayer Essentials
    {
        id: 'p1',
        vendorId: 'v1',
        categoryId: 'prayer-essentials',
        name: 'Premium Velvet Prayer Mat - Emerald',
        slug: 'premium-velvet-prayer-mat-emerald',
        description: 'Luxurious velvet prayer mat with intricate Islamic geometric patterns. Soft, durable, and non-slip backing.',
        price: 45.00,
        sku: 'PM-001',
        inventory: 50,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/prayer-rug-1.jpg',
        ],
        tags: ['prayer mat', 'velvet', 'premium', 'gift'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 24,
        salesCount: 150,
        viewsCount: 1200,
        createdAt: new Date('2023-01-15'),
        updatedAt: new Date('2023-01-15'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p1-b',
        vendorId: 'v1',
        categoryId: 'prayer-essentials',
        name: 'Handcrafted Misbaha Beads',
        slug: 'handcrafted-misbaha-beads',
        description: 'Beautiful 33-bead tasbih made from authentic olive wood. Smooth finish and durable stringing.',
        price: 18.00,
        sku: 'PM-002',
        inventory: 120,
        trackInventory: true,
        allowBackorders: true,
        images: [
            '/images/products/tasbih-1.jpg',
        ],
        tags: ['beads', 'tasbih', 'prayer', 'wood'],
        status: 'active',
        featured: false,
        rating: 4.7,
        reviewCount: 45,
        salesCount: 300,
        viewsCount: 900,
        createdAt: new Date('2023-01-20'),
        updatedAt: new Date('2023-01-20'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p12',
        vendorId: 'v1',
        categoryId: 'prayer-essentials',
        name: 'Digital Tasbih Counter',
        slug: 'digital-tasbih-counter',
        description: 'Modern electronic tasbih counter with LED display and silent mode. Ergonomic design for comfortable use.',
        price: 12.00,
        sku: 'PM-003',
        inventory: 150,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/tasbih-1.jpg'
        ],
        tags: ['tasbih', 'digital', 'prayer'],
        status: 'active',
        featured: false,
        rating: 4.6,
        reviewCount: 18,
        salesCount: 45,
        viewsCount: 320,
        createdAt: new Date('2023-09-01'),
        updatedAt: new Date('2023-09-01'),
        vendorName: 'Noor Essentials',
    },

    // Fragrances
    {
        id: 'p2',
        vendorId: 'v1',
        categoryId: 'fragrances',
        name: 'Oud Wood Essence',
        slug: 'oud-wood-essence',
        description: 'Rich and long-lasting Oud oil with notes of sandalwood and amber. Alcohol-free and pure.',
        price: 85.00,
        sku: 'FR-002',
        inventory: 30,
        trackInventory: true,
        allowBackorders: true,
        images: [
            '/images/products/tableware-1.jpg',
        ],
        tags: ['oud', 'perfume', 'oil', 'unisex'],
        status: 'active',
        featured: true,
        rating: 4.7,
        reviewCount: 18,
        salesCount: 95,
        viewsCount: 850,
        createdAt: new Date('2023-02-10'),
        updatedAt: new Date('2023-02-10'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p2-b',
        vendorId: 'v1',
        categoryId: 'fragrances',
        name: 'Rose & Musk Attar',
        slug: 'rose-musk-attar',
        description: 'Delicate blend of Taif rose and white musk. A refreshing scent for daily wear.',
        price: 35.00,
        sku: 'FR-003',
        inventory: 60,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/hijab-1.jpg',
        ],
        tags: ['attar', 'rose', 'perfume', 'alcohol-free'],
        status: 'active',
        featured: false,
        rating: 4.5,
        reviewCount: 12,
        salesCount: 80,
        viewsCount: 400,
        createdAt: new Date('2023-02-15'),
        updatedAt: new Date('2023-02-15'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p15',
        vendorId: 'v1',
        categoryId: 'fragrances',
        name: 'Luxury Bakhoor Oud Burner Set',
        slug: 'luxury-bakhoor-oud-burner-set',
        description: 'Complete set with a gold ceramic electric burner and premium Agarwood chips for a divine home scent.',
        price: 95.00,
        sku: 'FR-005',
        inventory: 12,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/tableware-1.jpg',
        ],
        tags: ['bakhoor', 'oud', 'burner', 'luxury'],
        status: 'active',
        featured: true,
        rating: 4.8,
        reviewCount: 5,
        salesCount: 12,
        viewsCount: 450,
        createdAt: new Date('2023-09-15'),
        updatedAt: new Date('2023-09-15'),
        vendorName: 'Noor Essentials',
    },

    // Modest Fashion
    {
        id: 'p3',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Silk Chiffon Hijab - Rose',
        slug: 'silk-chiffon-hijab-rose',
        description: 'Elegant silk chiffon hijab in a soft rose color. Lightweight and breathable, perfect for any occasion.',
        price: 25.00,
        sku: 'HJ-003',
        inventory: 100,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/hijab-1.jpg'
        ],
        tags: ['hijab', 'silk', 'fashion', 'modest'],
        status: 'active',
        featured: false,
        rating: 4.5,
        reviewCount: 42,
        salesCount: 210,
        viewsCount: 1500,
        createdAt: new Date('2023-03-05'),
        updatedAt: new Date('2023-03-05'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p4',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Embroidered Abaya',
        slug: 'embroidered-abaya',
        description: 'Classic black abaya with gold embroidery on cuffs and hem. Includes matching shayla.',
        price: 120.00,
        sku: 'AB-004',
        inventory: 15,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/abaya-1.jpg'
        ],
        tags: ['abaya', 'black', 'embroidered', 'luxury'],
        status: 'active',
        featured: true,
        rating: 5.0,
        reviewCount: 8,
        salesCount: 45,
        viewsCount: 600,
        createdAt: new Date('2023-03-20'),
        updatedAt: new Date('2023-03-20'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p18',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Lace Trim Silk Prayer Dress',
        slug: 'lace-trim-silk-prayer-dress',
        description: 'Complete one-piece prayer dress (mukena) made from soft premium silk with delicate lace trimmings.',
        price: 75.00,
        sku: 'AB-005',
        inventory: 25,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/prayer-rug-2.jpg'
        ],
        tags: ['mukena', 'prayer dress', 'silk', 'modest'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 15,
        salesCount: 50,
        viewsCount: 800,
        createdAt: new Date('2023-10-05'),
        updatedAt: new Date('2023-10-05'),
        vendorName: 'Modest Modern',
    },

    // Home Decor
    {
        id: 'p5',
        vendorId: 'v1',
        categoryId: 'home-decor',
        name: 'Islamic Calligraphy Wall Art',
        slug: 'islamic-calligraphy-wall-art',
        description: 'Beautiful "Ayat al-Kursi" metal wall art. Modern aesthetic perfect for living rooms.',
        price: 65.00,
        sku: 'HD-001',
        inventory: 20,
        trackInventory: true,
        allowBackorders: true,
        images: [
            '/images/products/wall-art-1.jpg'
        ],
        tags: ['decor', 'art', 'calligraphy', 'metal'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 30,
        salesCount: 120,
        viewsCount: 2000,
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date('2023-04-01'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p5-b',
        vendorId: 'v1',
        categoryId: 'home-decor',
        name: 'Moroccan Lantern',
        slug: 'moroccan-lantern',
        description: 'Gold-finished Moroccan lantern with colorful glass panels. Creates a warm, inviting atmosphere.',
        price: 28.00,
        sku: 'HD-002',
        inventory: 40,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/tableware-1.jpg'
        ],
        tags: ['lantern', 'lighting', 'decor', 'moroccan'],
        status: 'active',
        featured: false,
        rating: 4.6,
        reviewCount: 15,
        salesCount: 90,
        viewsCount: 500,
        createdAt: new Date('2023-04-10'),
        updatedAt: new Date('2023-04-10'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p13',
        vendorId: 'v1',
        categoryId: 'home-decor',
        name: 'Arabic Calligraphy Wall Clock',
        slug: 'arabic-calligraphy-wall-clock',
        description: 'Silent movement wall clock featuring beautiful "SubhanAllah" calligraphy. Minimalist design for any room.',
        price: 45.00,
        sku: 'HD-004',
        inventory: 15,
        trackInventory: true,
        allowBackorders: true,
        images: [
            '/images/products/wall-art-1.jpg'
        ],
        tags: ['clock', 'calligraphy', 'decor'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 12,
        salesCount: 28,
        viewsCount: 500,
        createdAt: new Date('2023-09-05'),
        updatedAt: new Date('2023-09-05'),
        vendorName: 'Noor Essentials',
    },

    // Islamic Books
    {
        id: 'p6',
        vendorId: 'v2',
        categoryId: 'books',
        name: 'Leather Bound Quran',
        slug: 'leather-bound-quran',
        description: 'Premium leather-bound Quran with golden edges. Uthmani script.',
        price: 55.00,
        sku: 'BK-001',
        inventory: 30,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/quran-1.jpg'
        ],
        tags: ['quran', 'book', 'islamic', 'gift'],
        status: 'active',
        featured: true,
        rating: 5.0,
        reviewCount: 60,
        salesCount: 400,
        viewsCount: 3000,
        createdAt: new Date('2023-04-15'),
        updatedAt: new Date('2023-04-15'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p6-b',
        vendorId: 'v2',
        categoryId: 'books',
        name: 'Collection of Hadith',
        slug: 'hadith-collection',
        description: 'Comprehensive collection of authentic Hadiths. Hardcover edition.',
        price: 40.00,
        sku: 'BK-002',
        inventory: 25,
        trackInventory: true,
        allowBackorders: true,
        images: [
            '/images/products/books-1.jpg'
        ],
        tags: ['hadith', 'book', 'learning', 'sunnah'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 22,
        salesCount: 110,
        viewsCount: 700,
        createdAt: new Date('2023-04-20'),
        updatedAt: new Date('2023-04-20'),
        vendorName: 'Modest Modern',
    },

    // Halal Food
    {
        id: 'p7',
        vendorId: 'v1',
        categoryId: 'halal-food',
        name: 'Premium Medjool Dates',
        slug: 'premium-medjool-dates',
        description: 'Large, sweet, and succulent Medjool dates. Rich in nutrients and perfect for breaking fast.',
        price: 24.00,
        sku: 'HF-001',
        inventory: 200,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/dates-gift-1.jpg'
        ],
        tags: ['dates', 'food', 'halal', 'ramadan'],
        status: 'active',
        featured: true,
        rating: 4.8,
        reviewCount: 35,
        salesCount: 500,
        viewsCount: 1200,
        createdAt: new Date('2023-05-01'),
        updatedAt: new Date('2023-05-01'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p7-b',
        vendorId: 'v1',
        categoryId: 'halal-food',
        name: 'Pure Sidr Honey',
        slug: 'pure-sidr-honey',
        description: '100% pure Sidr honey from the mountains. Known for its medicinal properties and exquisite taste.',
        price: 48.00,
        sku: 'HF-002',
        inventory: 15,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/6183561/pexels-photo-6183561.jpeg?auto=compress&cs=tinysrgb&w=1200'
        ],
        tags: ['honey', 'natural', 'halal', 'sunnah'],
        status: 'active',
        featured: false,
        rating: 5.0,
        reviewCount: 15,
        salesCount: 60,
        viewsCount: 300,
        createdAt: new Date('2023-05-05'),
        updatedAt: new Date('2023-05-05'),
        vendorName: 'Noor Essentials',
    },

    // Gifts
    {
        id: 'p8',
        vendorId: 'v2',
        categoryId: 'gifts',
        name: 'Islamic Gift Box - Ramadan Edition',
        slug: 'islamic-gift-box-ramadan',
        description: 'Beautifully curated gift box containing a prayer mat, tasbih, and a collection of Duas.',
        price: 75.00,
        sku: 'GT-001',
        inventory: 10,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1549439602-43ebca23d7af?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['gift', 'ramadan', 'box', 'set'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 10,
        salesCount: 40,
        viewsCount: 800,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date('2023-06-01'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p8-b',
        vendorId: 'v2',
        categoryId: 'gifts',
        name: 'Personalized Name Necklace',
        slug: 'personalized-name-necklace',
        description: 'Custom Arabic calligraphy name necklace in 18k gold plating. A unique and thoughtful gift.',
        price: 135.00,
        sku: 'GT-002',
        inventory: 5,
        trackInventory: true,
        allowBackorders: true,
        images: [
            'https://images.unsplash.com/photo-1515562141207-7a88bd7ce3ee?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['jewelry', 'custom', 'gift', 'gold'],
        status: 'active',
        featured: false,
        rating: 4.7,
        reviewCount: 5,
        salesCount: 20,
        viewsCount: 600,
        createdAt: new Date('2023-06-10'),
        updatedAt: new Date('2023-06-10'),
        vendorName: 'Modest Modern',
    },

    // Kids
    {
        id: 'p9',
        vendorId: 'v1',
        categoryId: 'kids',
        name: 'Islamic Storybook Set',
        slug: 'islamic-storybook-set',
        description: 'A set of 5 beautifully illustrated storybooks for kids to learn about Prophets and Islamic values.',
        price: 32.00,
        sku: 'KD-001',
        inventory: 45,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/4019754/pexels-photo-4019754.jpeg?auto=compress&cs=tinysrgb&w=800'
        ],
        tags: ['educational', 'books', 'kids'],
        status: 'active',
        featured: true,
        rating: 4.8,
        reviewCount: 20,
        salesCount: 110,
        viewsCount: 900,
        createdAt: new Date('2023-07-01'),
        updatedAt: new Date('2023-07-01'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p14',
        vendorId: 'v2',
        categoryId: 'kids',
        name: 'Ramadan Activity Fun Book',
        slug: 'ramadan-activity-fun-book',
        description: 'Creative and educational activity book for children to learn about Ramadan. Includes stickers and puzzles.',
        price: 15.00,
        sku: 'KD-003',
        inventory: 60,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['kids', 'book', 'ramadan', 'activity'],
        status: 'active',
        featured: false,
        rating: 5.0,
        reviewCount: 25,
        salesCount: 180,
        viewsCount: 900,
        createdAt: new Date('2023-09-10'),
        updatedAt: new Date('2023-09-10'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p11',
        vendorId: 'v2',
        categoryId: 'fragrances',
        name: 'Rare White Amber Oil',
        slug: 'rare-white-amber-oil',
        description: 'Extremely rare white amber oil. Limited edition release.',
        price: 180.00,
        sku: 'FR-004',
        inventory: 5,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/1961780/pexels-photo-1961780.jpeg?auto=compress&cs=tinysrgb&w=800',
        ],
        tags: ['rare', 'perfume', 'amber', 'luxury'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 1,
        salesCount: 15,
        viewsCount: 1000,
        createdAt: new Date('2023-08-10'),
        updatedAt: new Date('2023-08-10'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p21',
        vendorId: 'v2',
        categoryId: 'books',
        name: 'Prophetic Biography',
        slug: 'prophetic-biography',
        description: 'Detailed biography of the Prophet Muhammad (PBUH). Award-winning edition.',
        price: 35.00,
        sku: 'BK-003',
        inventory: 40,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['seerah', 'book', 'history'],
        status: 'active',
        featured: false,
        rating: 5.0,
        reviewCount: 15,
        salesCount: 80,
        viewsCount: 600,
        createdAt: new Date('2023-11-01'),
        updatedAt: new Date('2023-11-01'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p22',
        vendorId: 'v1',
        categoryId: 'halal-food',
        name: 'Organic Ajwa Dates',
        slug: 'organic-ajwa-dates',
        description: 'Authentic Ajwa dates from Madinah. Soft texture and natural sweetness.',
        price: 30.00,
        sku: 'HF-003',
        inventory: 150,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1543362906-acfc16c623a2?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['dates', 'halal', 'health'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 25,
        salesCount: 200,
        viewsCount: 800,
        createdAt: new Date('2023-11-05'),
        updatedAt: new Date('2023-11-05'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p23',
        vendorId: 'v2',
        categoryId: 'gifts',
        name: 'Islamic Greetings Card Set',
        slug: 'islamic-greetings-card-set',
        description: 'Elegant set of 10 greetings cards for Eid, weddings, and special Islamic occasions.',
        price: 15.00,
        sku: 'GT-003',
        inventory: 100,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/wall-art-1.jpg'
        ],
        tags: ['gift', 'cards', 'eid'],
        status: 'active',
        featured: false,
        rating: 4.8,
        reviewCount: 10,
        salesCount: 50,
        viewsCount: 300,
        createdAt: new Date('2023-11-10'),
        updatedAt: new Date('2023-11-10'),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p24',
        vendorId: 'v1',
        categoryId: 'kids',
        name: 'Islamic Alphabet Puzzle',
        slug: 'islamic-alphabet-puzzle',
        description: 'Large wooden floor puzzle to help children learn Arabic letters through play. Durable and colorful.',
        price: 28.00,
        sku: 'KD-004',
        inventory: 35,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['puzzle', 'educational', 'kids', 'arabic'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 12,
        salesCount: 40,
        viewsCount: 250,
        createdAt: new Date('2023-11-15'),
        updatedAt: new Date('2023-11-15'),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p25',
        vendorId: 'v1',
        categoryId: 'prayer-essentials',
        name: 'Cotton Travel Prayer Mat',
        slug: 'cotton-travel-prayer-mat',
        description: 'Lightweight and foldable cotton prayer mat with a pocket-sized carrying case. Perfect for the traveler.',
        price: 22.00,
        sku: 'PM-005',
        inventory: 200,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1596193810149-165c71a3372c?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['travel', 'prayer', 'cotton'],
        status: 'active',
        featured: false,
        rating: 4.8,
        reviewCount: 32,
        salesCount: 150,
        viewsCount: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p26',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Summer Kaftan Dress',
        slug: 'summer-kaftan-dress',
        description: 'Flowy and comfortable summer kaftan with ethnic prints and soft fabric.',
        price: 85.00,
        sku: 'AB-006',
        inventory: 40,
        trackInventory: true,
        allowBackorders: false,
        images: [
            '/images/products/kaftan-1.jpg'
        ],
        tags: ['kaftan', 'summer', 'modest', 'dress'],
        status: 'active',
        featured: true,
        rating: 4.7,
        reviewCount: 18,
        salesCount: 65,
        viewsCount: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p27',
        vendorId: 'v1',
        categoryId: 'fragrances',
        name: 'White Musk perfume Oil',
        slug: 'white-musk-perfume-oil',
        description: 'Pure and clean white musk oil. Refreshing scent that lasts all day.',
        price: 28.00,
        sku: 'FR-006',
        inventory: 80,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/4041391/pexels-photo-4041391.jpeg?auto=compress&cs=tinysrgb&w=800'
        ],
        tags: ['musk', 'oil', 'perfume'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 24,
        salesCount: 210,
        viewsCount: 1200,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p28',
        vendorId: 'v1',
        categoryId: 'home-decor',
        name: 'Ceramic Oud Burner - White',
        slug: 'ceramic-oud-burner-white',
        description: 'Handmade ceramic burner with a modern minimalist design. Ideal for bakhoor and oud.',
        price: 35.00,
        sku: 'HD-005',
        inventory: 50,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/4491881/pexels-photo-4491881.jpeg?auto=compress&cs=tinysrgb&w=1200'
        ],
        tags: ['burner', 'ceramic', 'decor', 'bakhoor'],
        status: 'active',
        featured: false,
        rating: 4.8,
        reviewCount: 15,
        salesCount: 45,
        viewsCount: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p29',
        vendorId: 'v2',
        categoryId: 'books',
        name: 'The Sealed Nectar',
        slug: 'the-sealed-nectar',
        description: 'A comprehensive book on the life of the Prophet Muhammad (PBUH).',
        price: 30.00,
        sku: 'BK-004',
        inventory: 60,
        trackInventory: true,
        allowBackorders: true,
        images: [
            'https://images.unsplash.com/photo-1589519160732-57fc498494f8?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['seerah', 'book', 'biography'],
        status: 'active',
        featured: true,
        rating: 5.0,
        reviewCount: 45,
        salesCount: 320,
        viewsCount: 1500,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p30',
        vendorId: 'v1',
        categoryId: 'halal-food',
        name: 'Premium Turkish Delight Box',
        slug: 'premium-turkish-delight-box',
        description: 'Authentic Turkish delights with various flavors including pistachio and rose.',
        price: 45.00,
        sku: 'HF-004',
        inventory: 100,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['turkish delight', 'halal', 'gift', 'food'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 22,
        salesCount: 180,
        viewsCount: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p31',
        vendorId: 'v2',
        categoryId: 'kids',
        name: 'Islamic Board Game',
        slug: 'islamic-board-game',
        description: 'Fun and educational board game for children to learn about Islamic history and values.',
        price: 38.00,
        sku: 'KD-005',
        inventory: 35,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1549439602-43ebca23d7af?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['kids', 'game', 'educational'],
        status: 'active',
        featured: false,
        rating: 4.8,
        reviewCount: 14,
        salesCount: 55,
        viewsCount: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p32',
        vendorId: 'v1',
        categoryId: 'prayer-essentials',
        name: 'Matte Finish Tasbih - Black',
        slug: 'matte-finish-tasbih-black',
        description: 'Elegant 99-bead tasbih with a soft matte finish and durable string.',
        price: 15.00,
        sku: 'PM-006',
        inventory: 150,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/1961780/pexels-photo-1961780.jpeg?auto=compress&cs=tinysrgb&w=1200'
        ],
        tags: ['tasbih', 'black', 'prayer'],
        status: 'active',
        featured: false,
        rating: 4.7,
        reviewCount: 20,
        salesCount: 300,
        viewsCount: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p33',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Jersey Hijab - Charcoal',
        slug: 'jersey-hijab-charcoal',
        description: 'Premium stretch jersey hijab. Soft, opaque, and pin-free.',
        price: 18.00,
        sku: 'HJ-004',
        inventory: 200,
        trackInventory: true,
        allowBackorders: true,
        images: [
            'https://images.unsplash.com/photo-1584281729288-665b16327318?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['hijab', 'jersey', 'fashion'],
        status: 'active',
        featured: false,
        rating: 4.9,
        reviewCount: 56,
        salesCount: 450,
        viewsCount: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p34',
        vendorId: 'v1',
        categoryId: 'fragrances',
        name: 'Amber Glow Attar',
        slug: 'amber-glow-attar',
        description: 'Warm and inviting amber attar with notes of vanilla and spice.',
        price: 45.00,
        sku: 'FR-007',
        inventory: 40,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.pexels.com/photos/1961780/pexels-photo-1961780.jpeg?auto=compress&cs=tinysrgb&w=1200'
        ],
        tags: ['attar', 'amber', 'perfume'],
        status: 'active',
        featured: false,
        rating: 4.8,
        reviewCount: 12,
        salesCount: 85,
        viewsCount: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p35',
        vendorId: 'v2',
        categoryId: 'modest-fashion',
        name: 'Embroidered Velvet Abaya',
        slug: 'embroidered-velvet-abaya',
        description: 'Luxurious velvet abaya with silver thread embroidery. Perfect for winter evenings.',
        price: 150.00,
        sku: 'AB-007',
        inventory: 15,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['abaya', 'velvet', 'luxury', 'winter'],
        status: 'active',
        featured: true,
        rating: 5.0,
        reviewCount: 9,
        salesCount: 30,
        viewsCount: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
    {
        id: 'p36',
        vendorId: 'v1',
        categoryId: 'home-decor',
        name: 'Arabic Alphabet Wall Stickers',
        slug: 'arabic-alphabet-wall-stickers',
        description: 'Colorful and educational wall stickers for kids bedrooms. Water-resistant and easy to apply.',
        price: 18.00,
        sku: 'HD-006',
        inventory: 120,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1510366810232-a5676352934b?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['kids', 'stickers', 'decor', 'arabic'],
        status: 'active',
        featured: false,
        rating: 4.6,
        reviewCount: 28,
        salesCount: 140,
        viewsCount: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Noor Essentials',
    },
    {
        id: 'p37',
        vendorId: 'v2',
        categoryId: 'books',
        name: 'Islamic History Encyclopedia',
        slug: 'islamic-history-encyclopedia',
        description: 'A massive 3-volume set covering the entire history of Islam from the beginning to the modern day.',
        price: 120.00,
        sku: 'BK-005',
        inventory: 10,
        trackInventory: true,
        allowBackorders: false,
        images: [
            'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=1200&auto=format&fit=crop'
        ],
        tags: ['history', 'book', 'encyclopedia'],
        status: 'active',
        featured: true,
        rating: 4.9,
        reviewCount: 15,
        salesCount: 40,
        viewsCount: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
        vendorName: 'Modest Modern',
    },
];

export const MOCK_REVIEWS: Review[] = [
    {
        id: 'r1',
        productId: 'p1',
        userId: 'u_test1',
        orderId: 'o1',
        rating: 5,
        title: 'Beautiful quality',
        content: 'The velvet feels amazing and the design is even better in person.',
        images: ['https://images.unsplash.com/photo-1597402490041-389f4109787c?w=400&h=400&fit=crop'],
        helpful: 2,
        verified: true,
        status: 'approved',
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date('2023-04-01'),
        userName: 'Fatima R.',
        userPhotoURL: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=100&h=100&fit=crop',
    },
    {
        id: 'r2',
        productId: 'p1',
        userId: 'u_test2',
        orderId: 'o2',
        rating: 4,
        title: 'Good but pricey',
        content: 'Great quality, but shipping took a bit longer (which is fine).',
        images: [],
        helpful: 0,
        verified: true,
        status: 'approved',
        createdAt: new Date('2023-04-05'),
        updatedAt: new Date('2023-04-05'),
        userName: 'Omar S.',
        userPhotoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    }
];
